${jsonencode(
{
    // This template specifies the available parameters for the different sizes of LogScale clusters
    "xsmall": {
        "logscale_digest_node_count": 3,
        "logscale_digest_instance_type": "i4i.2xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "gp2",
        "logscale_digest_data_disk_size": "3000Gi",
        "logscale_digest_min_node_count": 1,
        "logscale_digest_max_node_count": 3,
        "logscale_digest_desired_node_count": 3
        "logscale_digest_resources": {"limits": {"cpu": 7, "memory": "30Gi"}, "requests": {"cpu": 7, "memory": "30Gi"}},

        "logscale_ingress_node_count": 3,
        "logscale_ingress_instance_type": "c5.xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 1,
        "logscale_ingress_max_node_count": 3,
        "logscale_ingress_desired_node_count": 3,
        "logscale_ingress_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ingest_node_count": 3,
        "logscale_ingest_instance_type": "c5.xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 1,
        "logscale_ingest_max_node_count": 3,
        "logscale_ingest_desired_node_count": 3,
        "logscale_ingest_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ui_node_count": 3,
        "logscale_ui_instance_type": "c5.xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "128Gi",
        "logscale_ui_min_node_count": 1,
        "logscale_ui_max_node_count": 3,
        "logscale_ui_desired_node_count": 3,
        "logscale_ui_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "kafka_broker_node_count": 3,
        "kafka_broker_instance_type": "kafka.m5.large",
        "kafka_broker_min_node_count": 1,
        "kafka_broker_max_node_count": 3,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": 152,
    },
    "small": {
        "logscale_digest_node_count": 9,
        "logscale_digest_instance_type": "i4i.2xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 128,
        "logscale_digest_data_disk_type": "gp2",
        "logscale_digest_data_disk_size": "5800Gi",
        "logscale_digest_min_node_count": 3,
        "logscale_digest_max_node_count": 12,
        "logscale_digest_desired_node_count": 9,
        "logscale_digest_resources": {"limits": {"cpu": 7, "memory": "28Gi"}, "requests": {"cpu": 7, "memory": "28Gi"}},

        "logscale_ingress_node_count": 6,
        "logscale_ingress_instance_type": "c5.2xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 2,
        "logscale_ingress_max_node_count": 12,
        "logscale_ingress_desired_node_count": 9,
        "logscale_ingress_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ingest_node_count": 3,
        "logscale_ingest_instance_type": "c5.2xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 1,
        "logscale_ingest_max_node_count": 5,
        "logscale_ingest_desired_node_count": 3,
        "logscale_ingest_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ui_node_count": 3,
        "logscale_ui_instance_type": "c5.2xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "128Gi",
        "logscale_ui_min_node_count": 1,
        "logscale_ui_max_node_count": 5,
        "logscale_ui_desired_node_count": 3,
        "logscale_ui_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "kafka_broker_node_count": 6,
        "kafka_broker_instance_type": "kafka.m5.xlarge",
        "kafka_broker_min_node_count": 2,
        "kafka_broker_max_node_count": 8,
        "kafka_broker_desired_node_count": 6,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": 376,
    },
    "medium": {
        "logscale_digest_node_count": 21,
        "logscale_digest_instance_type": "i3en.3xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "gp2",
        "logscale_digest_data_disk_size": "11500Gi",
        "logscale_digest_min_node_count": 7,
        "logscale_digest_max_node_count": 30,
        "logscale_digest_desired_node_count": 21,
        "logscale_digest_resources": {"limits": {"cpu": 30, "memory": "120Gi"}, "requests": {"cpu": 30, "memory": "120Gi"}},

        "logscale_ingress_node_count": 12,
        "logscale_ingress_instance_type": "c5.4xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 4,
        "logscale_ingress_max_node_count": 16,
        "logscale_ingress_desired_node_count": 12,
        "logscale_ingress_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},

        "logscale_ingest_node_count": 6,
        "logscale_ingest_instance_type": "c5.4xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "250Gi",
        "logscale_ingest_min_node_count": 2,
        "logscale_ingest_max_node_count": 8,
        "logscale_ingest_desired_node_count": 6,
        "logscale_ingest_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},

        "logscale_ui_node_count": 6,
        "logscale_ui_instance_type": "c5.4xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "250Gi",
        "logscale_ui_min_node_count": 2,
        "logscale_ui_max_node_count": 8,
        "logscale_ui_desired_node_count": 6,
        "logscale_ui_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},

        "kafka_broker_node_count": 9,
        "kafka_broker_instance_type": "kafka.m5.4xlarge",
        "kafka_broker_min_node_count": 3,
        "kafka_broker_max_node_count": 12,
        "kafka_broker_desired_node_count": 9,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": 8000,
    },
    "large": {
        "logscale_digest_node_count": 42,
        "logscale_digest_instance_type": "i3en.12xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "gp2",
        "logscale_digest_data_disk_size": "11500Gi",
        "logscale_digest_min_node_count": 14,
        "logscale_digest_max_node_count": 56,
        "logscale_digest_desired_node_count": 42,
        "logscale_digest_resources": {"limits": {"cpu": 30, "memory": "120Gi"}, "requests": {"cpu": 30, "memory": "120Gi"}},

        "logscale_ingress_node_count": 18,
        "logscale_ingress_instance_type": "c5.9xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 6,
        "logscale_ingress_max_node_count": 24,
        "logscale_ingress_desired_node_count": 18,
        "logscale_ingress_resources": {"limits": {"cpu": 15, "memory": "30Gi"}, "requests": {"cpu": 15, "memory": "30Gi"}},

        "logscale_ingest_node_count": 9,
        "logscale_ingest_instance_type": "c5.9xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 3,
        "logscale_ingest_max_node_count": 12,
        "logscale_ingest_desired_node_count": 9,
        "logscale_ingest_resources": {"limits": {"cpu": 15, "memory": "30Gi"}, "requests": {"cpu": 15, "memory": "30Gi"}},

        "logscale_ui_node_count": 9,
        "logscale_ui_instance_type": "c5.9xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "500Gi",
        "logscale_ui_min_node_count": 3,
        "logscale_ui_max_node_count": 12,
        "logscale_ui_desired_node_count": 9,
        "logscale_ui_resources": {"limits": {"cpu": 15, "memory": "30Gi"}, "requests": {"cpu": 7, "memory": "30Gi"}},

        "kafka_broker_node_count": 9,
        "kafka_broker_instance_type": "kafka.m5.8xlarge",
        "kafka_broker_min_node_count": 3,
        "kafka_broker_max_node_count": 12,
        "kafka_broker_desired_node_count": 9,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": 2504,
    },
    "xlarge": {
        "logscale_digest_node_count": 78,
        "logscale_digest_instance_type": "i3en.12xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "gp2",
        "logscale_digest_data_disk_size": "11500Gi",
        "logscale_digest_min_node_count": 26,
        "logscale_digest_max_node_count": 104,
        "logscale_digest_desired_node_count": 78,
        "logscale_digest_resources": {"limits": {"cpu": 46, "memory": "184Gi"}, "requests": {"cpu": 46, "memory": "184Gi"}},

        "logscale_ingress_node_count": 36,
        "logscale_ingress_instance_type": "c5.12xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 18,
        "logscale_ingress_max_node_count": 52,
        "logscale_ingress_desired_node_count": 36,
        "logscale_ingress_resources": {"limits": {"cpu": 15, "memory": "30Gi"}, "requests": {"cpu": 15, "memory": "30Gi"}},

        "logscale_ingest_node_count": 18,
        "logscale_ingest_instance_type": "c5.12xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "500Gi",
        "logscale_ingest_min_node_count": 12,
        "logscale_ingest_max_node_count": 28,
        "logscale_ingest_desired_node_count": 18,
        "logscale_ingest_resources": {"limits": {"cpu": 30, "memory": "30Gi"}, "requests": {"cpu": 30, "memory": "30Gi"}},

        "logscale_ui_node_count": 18,
        "logscale_ui_instance_type": "c5.12xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "500Gi",
        "logscale_ui_min_node_count": 12,
        "logscale_ui_max_node_count": 28,
        "logscale_ui_desired_node_count": 18,
        "logscale_ui_resources": {"limits": {"cpu": 30, "memory": "30Gi"}, "requests": {"cpu": 30, "memory": "30Gi"}},

        "kafka_broker_node_count": 18,
        "kafka_broker_instance_type": "kafka.m5.8xlarge",
        "kafka_broker_min_node_count": 3,
        "kafka_broker_max_node_count": 24,
        "kafka_broker_desired_node_count": 18,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": 2504,
    },
}
)}
