${jsonencode(
{
    // This template specifies the available parameters for the different sizes of LogScale clusters
    "xsmall": {
        "kafka_broker_node_count": 3,
        "kafka_broker_pod_replica_count": 3,
        "kafka_broker_instance_type": "kafka.m5.xlarge",
        "kafka_broker_resources": {"limits": {"cpu": 3, "memory": "12Gi"}, "requests": {"cpu": 3, "memory": "12Gi"}},
        "kafka_broker_min_node_count": 3,
        "kafka_broker_max_node_count": 3,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": "1024Gi",

        "logscale_digest_pod_count": 3,
        "logscale_digest_instance_type": "i3en.2xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "topolvm-provisioner",
        "logscale_digest_data_disk_size": "4500Gi",
        "logscale_digest_min_node_count": 3,
        "logscale_digest_max_node_count": 3,
        "logscale_digest_desired_node_count": 3
        "logscale_digest_resources": {"limits": {"cpu": 6, "memory": "30Gi"}, "requests": {"cpu": 6, "memory": "30Gi"}},

        "logscale_ingress_pod_count": 3,
        "logscale_ingress_instance_type": "c5.xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 3,
        "logscale_ingress_max_node_count": 3,
        "logscale_ingress_desired_node_count": 3,
        "logscale_ingress_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ingest_pod_count": 3,
        "logscale_ingest_instance_type": "c5.xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 3,
        "logscale_ingest_max_node_count": 3,
        "logscale_ingest_desired_node_count": 3,
        "logscale_ingest_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ui_pod_count": 3,
        "logscale_ui_instance_type": "c5.xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "128Gi",
        "logscale_ui_min_node_count": 3,
        "logscale_ui_max_node_count": 3,
        "logscale_ui_desired_node_count": 3,
        "logscale_ui_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},
    },
    "small": {
        "kafka_broker_node_count": 6,
        "kafka_broker_pod_replica_count": 6,
        "kafka_broker_instance_type": "kafka.m5.2xlarge",
        "kafka_broker_resources": {"limits": {"cpu": 6, "memory": "28Gi"}, "requests": {"cpu": 6, "memory": "28Gi"}},
        "kafka_broker_min_node_count": 6,
        "kafka_broker_max_node_count": 8,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": "1024Gi",

        "logscale_digest_pod_count": 9,
        "logscale_digest_instance_type": "i3en.2xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 128,
        "logscale_digest_data_disk_type": "topolvm-provisioner",
        "logscale_digest_data_disk_size": "4500Gi",
        "logscale_digest_min_node_count": 9,
        "logscale_digest_max_node_count": 12,
        "logscale_digest_desired_node_count": 9,
        "logscale_digest_resources": {"limits": {"cpu": 7, "memory": "52Gi"}, "requests": {"cpu": 7, "memory": "52Gi"}},

        "logscale_ingress_pod_count": 6,
        "logscale_ingress_instance_type": "c5.xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 6,
        "logscale_ingress_max_node_count": 12,
        "logscale_ingress_desired_node_count": 6,
        "logscale_ingress_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ingest_pod_count": 3,
        "logscale_ingest_instance_type": "c5.xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 3,
        "logscale_ingest_max_node_count": 5,
        "logscale_ingest_desired_node_count": 3,
        "logscale_ingest_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},

        "logscale_ui_pod_count": 3,
        "logscale_ui_instance_type": "c5.xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "128Gi",
        "logscale_ui_min_node_count": 3,
        "logscale_ui_max_node_count": 5,
        "logscale_ui_desired_node_count": 3,
        "logscale_ui_resources": {"limits": {"cpu": 3, "memory": "6Gi"}, "requests": {"cpu": 3, "memory": "6Gi"}},
    },
    "medium": {
        "kafka_broker_node_count": 9,
        "kafka_broker_pod_replica_count": 9,
        "kafka_broker_instance_type": "kafka.m5.4xlarge",
        "kafka_broker_resources": {"limits": {"cpu": 14, "memory": "56Gi"}, "requests": {"cpu": 14, "memory": "56Gi"}},
        "kafka_broker_min_node_count": 9,
        "kafka_broker_max_node_count": 12,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": "1024Gi",

        "logscale_digest_pod_count": 21,
        "logscale_digest_instance_type": "i3en.3xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "topolvm-provisioner",
        "logscale_digest_data_disk_size": "6820Gi",
        "logscale_digest_min_node_count": 21,
        "logscale_digest_max_node_count": 30,
        "logscale_digest_desired_node_count": 21,
        "logscale_digest_resources": {"limits": {"cpu": 9, "memory": "80Gi"}, "requests": {"cpu": 9, "memory": "80Gi"}},

        "logscale_ingress_pod_count": 12,
        "logscale_ingress_instance_type": "c5.2xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 12,
        "logscale_ingress_max_node_count": 16,
        "logscale_ingress_desired_node_count": 12,
        "logscale_ingress_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},

        "logscale_ingest_pod_count": 6,
        "logscale_ingest_instance_type": "c5.2xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "250Gi",
        "logscale_ingest_min_node_count": 6,
        "logscale_ingest_max_node_count": 8,
        "logscale_ingest_desired_node_count": 6,
        "logscale_ingest_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},

        "logscale_ui_pod_count": 6,
        "logscale_ui_instance_type": "c5.2xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "250Gi",
        "logscale_ui_min_node_count": 6,
        "logscale_ui_max_node_count": 8,
        "logscale_ui_desired_node_count": 6,
        "logscale_ui_resources": {"limits": {"cpu": 7, "memory": "14Gi"}, "requests": {"cpu": 7, "memory": "14Gi"}},
    },
    "large": {
        "kafka_broker_node_count": 9,
        "kafka_broker_pod_replica_count": 9,
        "kafka_broker_instance_type": "kafka.m5.8xlarge",
        "kafka_broker_resources": {"limits": {"cpu": 28, "memory": "118Gi"}, "requests": {"cpu": 28, "memory": "118Gi"}},
        "kafka_broker_min_node_count": 9,
        "kafka_broker_max_node_count": 12,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": "2048Gi",

        "logscale_digest_pod_count": 42,
        "logscale_digest_instance_type": "i3en.12xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "topolvm-provisioner",
        "logscale_digest_data_disk_size": "11500Gi",
        "logscale_digest_min_node_count": 42,
        "logscale_digest_max_node_count": 56,
        "logscale_digest_desired_node_count": 42,
        "logscale_digest_resources": {"limits": {"cpu": 44, "memory": "360Gi"}, "requests": {"cpu": 44, "memory": "360Gi"}},

        "logscale_ingress_pod_count": 18,
        "logscale_ingress_instance_type": "c5.4xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 18,
        "logscale_ingress_max_node_count": 24,
        "logscale_ingress_desired_node_count": 18,
        "logscale_ingress_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},

        "logscale_ingest_pod_count": 9,
        "logscale_ingest_instance_type": "c5.4xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "128Gi",
        "logscale_ingest_min_node_count": 9,
        "logscale_ingest_max_node_count": 12,
        "logscale_ingest_desired_node_count": 9,
        "logscale_ingest_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},

        "logscale_ui_pod_count": 9,
        "logscale_ui_instance_type": "c5.4xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "500Gi",
        "logscale_ui_min_node_count": 9,
        "logscale_ui_max_node_count": 12,
        "logscale_ui_desired_node_count": 9,
        "logscale_ui_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},
    },
    "xlarge": {
        "kafka_broker_node_count": 18,
        "kafka_broker_pod_replica_count": 18,
        "kafka_broker_instance_type": "kafka.m5.8xlarge",
        "kafka_broker_resources": {"limits": {"cpu": 28, "memory": "118Gi"}, "requests": {"cpu": 28, "memory": "118Gi"}},
        "kafka_broker_min_node_count": 18,
        "kafka_broker_max_node_count": 24,
        "kafka_broker_data_disk_type": "gp2",
        "kafka_broker_data_disk_size": "2048Gi",
        
        "logscale_digest_pod_count": 78,
        "logscale_digest_instance_type": "i3en.12xlarge",
        "logscale_digest_root_disk_type": "gp2",
        "logscale_digest_root_disk_size": 20,
        "logscale_digest_data_disk_type": "topolvm-provisioner",
        "logscale_digest_data_disk_size": "11500Gi",
        "logscale_digest_min_node_count": 78,
        "logscale_digest_max_node_count": 104,
        "logscale_digest_desired_node_count": 78,
        "logscale_digest_resources": {"limits": {"cpu": 44, "memory": "360Gi"}, "requests": {"cpu": 44, "memory": "360Gi"}},

        "logscale_ingress_pod_count": 36,
        "logscale_ingress_instance_type": "c5.4xlarge",
        "logscale_ingress_root_disk_size": 20,
        "logscale_ingress_root_disk_type": "gp2",
        "logscale_ingress_data_disk_type": "gp2",
        "logscale_ingress_data_disk_size": "128Gi",
        "logscale_ingress_min_node_count": 36,
        "logscale_ingress_max_node_count": 52,
        "logscale_ingress_desired_node_count": 36,
        "logscale_ingress_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},

        "logscale_ingest_pod_count": 18,
        "logscale_ingest_instance_type": "c5.4xlarge",
        "logscale_ingest_root_disk_type": "gp2",
        "logscale_ingest_root_disk_size": 20,
        "logscale_ingest_data_disk_type": "gp2",
        "logscale_ingest_data_disk_size": "500Gi",
        "logscale_ingest_min_node_count": 18,
        "logscale_ingest_max_node_count": 28,
        "logscale_ingest_desired_node_count": 18,
        "logscale_ingest_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},

        "logscale_ui_pod_count": 18,
        "logscale_ui_instance_type": "c5.4xlarge",
        "logscale_ui_root_disk_type": "gp2",
        "logscale_ui_root_disk_size": 20,
        "logscale_ui_data_disk_type": "gp2",
        "logscale_ui_data_disk_size": "500Gi",
        "logscale_ui_min_node_count": 18,
        "logscale_ui_max_node_count": 28,
        "logscale_ui_desired_node_count": 18,
        "logscale_ui_resources": {"limits": {"cpu": 15, "memory": "26Gi"}, "requests": {"cpu": 15, "memory": "26Gi"}},
    },
}
)}
